### PR TITLE
Fix bug that chunked encoding ends without last-chunk

### LINKED ISSUE #20: chunked transfer-encoding terminates without last-chunk
llhttp terminates chunked encoding without last-chunk ('0' + '\r\n').

For example, if I send the following request:
```
PUT / HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding: chunked\r\n\r\n1\r\nx\r\n\r\n\r\n
```

llhttp reports that request body completes.
According to RFC 7230 [1], chunked encoding requires last-chunk.

[1]: https://tools.ietf.org/html/rfc7230#section-4.1

### PR DESCRIPTION
**Pull request by tatsuhiro-t**
This change fixes the bug that chunked encoding can end without seeing last-chunk.  More specifically, reading just extra `\r\n\r\n` persuades llhttp that chunked encoding finished.

Fixes #20

### CODE REVIEW

File: src/llhttp/http.ts [hunk 1]
```diff
@@ -594,7 +595,15 @@ export class HTTP {
     n('chunk_size')
       .select(HEX_MAP, this.mulAdd('content_length', {
```
Comment (indutny) [inline src/llhttp/http.ts]: Let's move `this.mulAdd('content_length', ...)` to a shared declaration like this:

```js
const addContentLength = this.mulAdd('content_length', { ... });

n('chunk_size').select(HEX_MAP, addContentLength)...
n('chunk_size2').select(HEX_MAP, addContentLength)...
```

File: src/llhttp/http.ts [hunk 2]
```diff
@@ -594,7 +595,15 @@ export class HTTP {
     n('chunk_size')
```
Comment (indutny) [inline src/llhttp/http.ts]: Perhaps, this should be `chunk_size_digit` and below should be just `chunk_size`?

**Comment by tatsuhiro-t** [comment]
@indutny Thank you for the comments.  I made changes as you suggested.

**Comment by indutny** [comment]
Excellent. This looks great!

One last thing: could you also add a regression test here: https://github.com/nodejs/llhttp/blob/master/test/request/transfer-encoding.md ? The way I usually approach this is by adding a new request at the end of that `md` file, removing everything in `log` section and replacing it with what test suite outputs. Please feel free to ask any question about it. The process is not ideal and I'll be glad to help!

**Comment by tatsuhiro-t** [comment]
When I run md-test.ts, I got `ReferenceError: describe is not defined` error.  My knowledge is very much limited when it comes to node/ts-node/node, no idea how to fix it.

**Comment by tatsuhiro-t** [comment]
Sorry, it started working.  Will see what happens.

**Comment by tatsuhiro-t** [comment]
OK, added a regression test.

**Comment by indutny** [comment]
This might be a bit out-of-context, but if you don't mind me asking: how do you use or plan to use llhttp? :wink:

**Comment by tatsuhiro-t** [comment]
I just replaced http-parser with llhttp in [nghttp2](https://github.com/nghttp2/nghttp2).  I still need URL paser, so I extract it from http-parser.

**Comment by indutny** [comment]
Awesome. Thank you!

**Comment by indutny** [comment]
I've released 1.1.2 with your change.
